'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,CalendarDays,Check,ClipboardList,Download,Plus,RefreshCw,Search,SlidersHorizontal,Users,ScanLine} from 'lucide-react';
import QRCode from 'qrcode';
import {api,dateLabel} from '@/lib/client/api';
import type {Patient,ProfileInput,ListeningEvent,Pairing} from '@/lib/types';
import {difficulties,frequencies} from '@/lib/types';
import {Header,Footer,ErrorBox,Loading,Status,Audiogram,AcousticResult} from './shared';
const sample:ProfileInput={displayName:'',audiogram:{frequencies,left:[25,30,40,45,55,60],right:[20,25,35,40,50,55]},aids:{side:'bilateral',left:{model:'Widex ALLURE BTE R D',tier:'220'},right:{model:'Widex ALLURE BTE R D',tier:'220'}},followUpDate:'2026-09-28',note:'',timezone:'Europe/Prague'};
export function ClinicDirectory(){
 const [patients,setPatients]=useState<Patient[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState(''),[difficulty,setDifficulty]=useState(''),[followUp,setFollowUp]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
 useEffect(()=>{let active=true;const timer=setTimeout(async()=>{try{await api('/api/session');const result=await api<{patients:Patient[]}>(`/api/patients?${new URLSearchParams({q,status,difficulty,followUp})}`);if(active){setPatients(result.patients);setError('');}}catch(e){if(active)setError((e as Error).message);}finally{if(active)setLoading(false);}},q?250:0);return()=>{active=false;clearTimeout(timer);};},[q,status,difficulty,followUp,version]);
 useEffect(()=>{const id=setInterval(()=>setVersion(v=>v+1),8000);return()=>clearInterval(id);},[]);
 return <><Header/><main id="main" className="clinic-main page-width"><div className="page-title-row"><div><span className="eyebrow">Clinician space <span className="label-pill">Illustrative demo</span></span><h1>People, before patterns.</h1><p>A clearer view of everyday listening, one person at a time.</p></div><Link href="/clinic/patients/new" className="button"><Plus size={19}/>Create demo patient</Link></div>
 <div className="directory-banner glass"><div className="banner-symbol"><Users size={23}/></div><div><strong>Your own demo space</strong><p>Use synthetic names and audiograms. Only this browser and phones you pair can access these profiles.</p></div><span className="quiet-tag">Private by default</span></div>
 <div className="directory-toolbar"><label className="search-box"><Search size={20}/><input type="search" placeholder="Search names, notes or listening moments" aria-label="Search patients and event content" value={q} onChange={e=>setQ(e.target.value)}/></label><div className="filter-row"><SlidersHorizontal size={18} aria-hidden/><label><span className="sr-only">Result status</span><select aria-label="Result status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Any result</option><option value="ready">Ready</option><option value="queued">Queued</option><option value="analysing">Analysing</option><option value="failed">Failed</option></select></label><label><span className="sr-only">Reported difficulty</span><select aria-label="Reported difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">Any difficulty</option>{difficulties.map(d=><option key={d}>{d}</option>)}</select></label><label className="date-filter"><span>Follow-up by</span><input type="date" aria-label="Follow-up by" value={followUp} onChange={e=>setFollowUp(e.target.value)}/></label></div></div>
 {error&&<ErrorBox message={error}/>}<div className="list-heading"><span>{patients.length} {patients.length===1?'profile':'profiles'}</span><span>Results refresh automatically</span></div>
 {loading?<Loading/>:patients.length===0?<section className="empty-state glass"><span className="empty-icon"><Users size={35} strokeWidth={1.3}/></span><h2>{q||status||difficulty||followUp?'No matching profiles':'A new listening story starts here.'}</h2><p>{q||status||difficulty||followUp?'Try another search or clear your filters.':'Create a synthetic profile, then pair a phone to capture your first listening moment.'}</p><Link className="button" href="/clinic/patients/new"><Plus size={18}/>Create demo patient</Link></section>:<div className="patient-grid">{patients.map((p,i)=><Link className="patient-card glass" href={'/clinic/patients/'+p.id} key={p.id}><div className="patient-card-top"><span className={'avatar '+(i%2?'peach':'sage')}>{p.displayName.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><span className="card-arrow"><ArrowRight size={19}/></span></div><h2>{p.displayName}</h2><span className="caption">Synthetic demo profile</span><div className="aid-summary"><AudioAid side={p.aids.side}/><span>{p.aids.side==='bilateral'?'Both ears':p.aids.side==='left'?'Left ear':'Right ear'} · ALLURE BTE R D</span></div><div className="patient-card-bottom"><span><CalendarDays size={15}/>{dateLabel(p.followUpDate)}</span><span>{p.eventCount||0} moments</span></div>{p.latestStatus&&<Status value={p.latestStatus}/>}</Link>)}</div>}
 <aside className="clinic-footnote">Clinical interpretation remains with the clinician. Phone audio is not calibrated sound pressure and cannot be compared directly with an audiogram.</aside></main><Footer/></>;
}
function AudioAid({side}:{side:string}){return <span className="ear-mark" aria-hidden>{side==='bilateral'?'L + R':side==='left'?'L':'R'}</span>;}
export function PatientForm({initial,onSaved}:{initial?:Patient;onSaved?:(p:Patient)=>void}){
 const [value,setValue]=useState<ProfileInput>(initial||sample),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 function field<K extends keyof ProfileInput>(name:K,data:ProfileInput[K]){setValue(v=>({...v,[name]:data}));}
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await api('/api/session');const result=await api<{patient:Patient}>(initial?'/api/patients/'+initial.id:'/api/patients',{method:initial?'PATCH':'POST',body:JSON.stringify(value)});if(onSaved)onSaved(result.patient);else window.location.href='/clinic/patients/'+result.patient.id;}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <form className="patient-form" onSubmit={submit}><section className="glass form-section"><span className="eyebrow">01 · The person</span><h2>A simple demo profile</h2><div className="form-grid"><label>Display name<input required maxLength={80} autoComplete="off" placeholder="For example, Alex Morgan" value={value.displayName} onChange={e=>field('displayName',e.target.value)}/><span className="caption">Use a made-up name. No real patient details.</span></label><label>Next follow-up<input type="date" required value={value.followUpDate} onChange={e=>field('followUpDate',e.target.value)}/></label><label className="wide">Brief demo note <span className="optional">optional</span><textarea maxLength={500} rows={2} placeholder="For example, exploring conversation in busy cafés." value={value.note} onChange={e=>field('note',e.target.value)}/></label><label>Clinic timezone<select value={value.timezone} onChange={e=>field('timezone',e.target.value)}><option>Europe/Prague</option><option>Europe/London</option><option>America/New_York</option><option>UTC</option></select></label></div></section>
 <section className="glass form-section"><span className="eyebrow">02 · Hearing profile</span><h2>Synthetic audiogram</h2><p className="caption">Clinician-entered hearing thresholds in dB HL. These example values are editable and are not a fitting recommendation.</p><div className="audiogram-form-layout"><div className="audiogram-inputs"><table><thead><tr><th scope="col">Hz</th><th scope="col">× Left ear</th><th scope="col">○ Right ear</th></tr></thead><tbody>{frequencies.map((hz,i)=><tr key={hz}><th scope="row">{hz.toLocaleString('en')}</th>{(['left','right'] as const).map(ear=><td key={ear}><input aria-label={`${ear==='left'?'Left':'Right'} ear ${hz} Hz dB HL`} type="number" required min={-10} max={120} step={5} value={value.audiogram[ear][i]} onChange={e=>field('audiogram',{...value.audiogram,[ear]:value.audiogram[ear].map((v,j)=>i===j?Number(e.target.value):v)})}/></td>)}</tr>)}</tbody></table></div><Audiogram data={value.audiogram}/></div></section>
 <section className="glass form-section"><span className="eyebrow">03 · Current hearing aids</span><h2>What they use today</h2><div className="form-grid"><label className="wide">Fitted ears<select value={value.aids.side} onChange={e=>{const side=e.target.value as ProfileInput['aids']['side'];field('aids',{side,left:side==='right'?null:value.aids.left||{model:'Widex ALLURE BTE R D',tier:'220'},right:side==='left'?null:value.aids.right||{model:'Widex ALLURE BTE R D',tier:'220'}});}}><option value="bilateral">Both ears</option><option value="left">Left ear</option><option value="right">Right ear</option></select></label>{(['left','right'] as const).map(ear=>value.aids[ear]&&<fieldset key={ear}><legend>{ear==='left'?'Left':'Right'} hearing aid</legend><label>Model<select value={value.aids[ear]!.model} onChange={()=>{}}><option>Widex ALLURE BTE R D</option></select></label><label>Tier<select value={value.aids[ear]!.tier} onChange={e=>field('aids',{...value.aids,[ear]:{...value.aids[ear]!,tier:e.target.value}})}>{['110','220','330','440'].map(t=><option key={t}>{t}</option>)}</select></label></fieldset>)}</div><p className="caption">Illustrative device scope. Tier-specific differences are not inferred. Earmold and venting decisions remain outside this demo.</p></section>
 {error&&<ErrorBox message={error}/>}<div className="form-footer"><p>Synthetic information only. This is an illustrative demo.</p><button className="button" disabled={saving}>{saving?'Saving profile…':initial?'Save profile':'Create demo profile'}<ArrowRight size={18}/></button></div></form>;
}
export function NewPatient(){return <><Header/><main id="main" className="form-main page-width"><Link className="back-link" href="/clinic"><ArrowLeft size={17}/>All patients</Link><div className="page-title-row"><div><span className="eyebrow">A thoughtful beginning</span><h1>Create a demo patient.</h1><p>A little context now makes future listening moments more useful.</p></div></div><PatientForm/></main><Footer/></>;}
export function PatientCard({id}:{id:string}){
 const [patient,setPatient]=useState<Patient|null>(null),[events,setEvents]=useState<ListeningEvent[]>([]),[pairing,setPairing]=useState<Pairing|null>(null),[qr,setQr]=useState(''),[error,setError]=useState(''),[editing,setEditing]=useState(false),[pairingBusy,setPairingBusy]=useState(false),[report,setReport]=useState<{status:string;url?:string}|null>(null),[reportBusy,setReportBusy]=useState(false);
 useEffect(()=>{let active=true;async function load(){try{const result=await api<{patient:Patient;events:ListeningEvent[];pairing:Pairing|null}>('/api/patients/'+id);if(active){setPatient(result.patient);setEvents(result.events);if(result.pairing)setPairing(result.pairing);setError('');}const rep=await api<{status:string;url?:string}>('/api/patients/'+id+'/report');if(active)setReport(rep);}catch(e){if(active)setError((e as Error).message);}}void load();const timer=setInterval(load,5000);return()=>{active=false;clearInterval(timer);};},[id]);
 useEffect(()=>{if(pairing)void QRCode.toDataURL(pairing.url,{width:320,margin:2,color:{dark:'#234638',light:'#ffffff'},errorCorrectionLevel:'M'}).then(setQr);else setQr('');},[pairing]);
 async function createPairing(){setPairingBusy(true);try{const result=await api<{pairing?:Pairing}&Pairing>('/api/patients/'+id+'/pairing',{method:'POST',body:'{}'});setPairing(result.pairing||result);setError('');}catch(e){setError((e as Error).message);}finally{setPairingBusy(false);}}
 async function revoke(){setPairingBusy(true);try{await api('/api/patients/'+id+'/pairing',{method:'DELETE'});setPairing(null);setQr('');}catch(e){setError((e as Error).message);}finally{setPairingBusy(false);}}
 async function requestReport(){setReportBusy(true);try{const result=await api<{status:string}>('/api/patients/'+id+'/report',{method:'POST',body:'{}'});setReport(result);}catch(e){setError((e as Error).message);}finally{setReportBusy(false);}}
 return <><Header/><main id="main" className="clinic-main page-width"><Link href="/clinic" className="back-link"><ArrowLeft size={17}/>All patients</Link>{error&&<ErrorBox message={error}/>} {!patient?<Loading label="Opening patient profile…"/>: <><div className="page-title-row"><div><span className="eyebrow">Synthetic demo patient</span><h1>{patient.displayName}</h1><p><CalendarDays size={17} className="inline-icon"/>Next conversation · {dateLabel(patient.followUpDate)}</p></div><button className="button secondary" onClick={()=>setEditing(!editing)}>{editing?'Close setup':'Edit profile'}</button></div>
 {editing?<PatientForm initial={patient} onSaved={p=>{setPatient(p);setEditing(false);}}/>:<><div className="patient-overview"><section className="glass overview-profile"><div className="card-heading"><h2>The hearing profile</h2><span className="quiet-tag">Versioned with each moment</span></div><Audiogram data={patient.audiogram}/><div className="aid-pills">{(['left','right'] as const).map(ear=>patient.aids[ear]&&<span key={ear}><strong>{ear==='left'?'L':'R'}</strong>{patient.aids[ear]!.model} · {patient.aids[ear]!.tier}</span>)}</div>{patient.note&&<p className="profile-note">{patient.note}</p>}</section>
 <section className="glass pairing-card"><span className="eyebrow"><ScanLine size={16}/> A simple connection</span><h2>Bring a phone into<br/>the conversation.</h2>{pairing?<><div className="qr-container">{qr&&<img src={qr} width="210" height="210" alt="QR code for this demo profile’s opaque pairing link"/>}</div><p>Scan with your phone’s camera, then confirm the profile.</p><label className="pairing-code">Manual pairing code<code data-testid="pairing-code">{pairing.code}</code></label><p className="caption">Expires {dateLabel(pairing.expiresAt)}. This link grants demo access; it is not clinical authentication.</p>{pairing.url.includes('localhost')&&<div className="notice">This URL works on this computer only. Cross-device pairing requires a configured, reachable HTTPS development origin.</div>}<Link className="text-button" href={pairing.url}>Open pairing link <ArrowRight size={16}/></Link><div className="pairing-controls"><button className="text-button" disabled={pairingBusy} onClick={createPairing}><RefreshCw size={14}/>Replace code</button><button className="text-button danger" disabled={pairingBusy} onClick={revoke}>Revoke access</button></div></>:<><div className="pairing-placeholder"><ScanLine size={65} strokeWidth={1}/></div><p>Create a private pairing link for this demo profile. Replacing it disconnects previously paired phones.</p><button className="button" disabled={pairingBusy} onClick={createPairing}>{pairingBusy?'Creating pairing…':'Create pairing QR'}<ArrowRight size={17}/></button></>}</section></div>
 <section className="moments-section"><div className="section-title-row"><div><span className="eyebrow">Everyday evidence</span><h2>Listening moments <span className="count-pill">{events.length}</span></h2></div><div className="report-actions">{report?.status==='ready'&&report.url?<a className="button secondary" href={report.url}><Download size={18}/>Download PDF report</a>:<button className="button secondary" disabled={reportBusy||report?.status==='queued'||report?.status==='generating'} onClick={requestReport}><ClipboardList size={18}/>{report?.status==='queued'||report?.status==='generating'?'Preparing report…':'Prepare PDF report'}</button>}</div></div>{events.length===0?<div className="empty-state compact glass"><h3>A first moment is waiting.</h3><p>Pair a phone and choose either patient action. Real acoustic results will appear here after processing.</p></div>:<div className="detailed-events">{events.map(event=><article className="glass event-detail-card" id={'event-'+event.id} key={event.id}><div className="event-detail-top"><span className={'moment-icon '+event.kind}>{event.kind==='understood'?<Check size={23}/>:<SlidersHorizontal size={23}/>}</span><div><h3>{event.kind==='understood'?'I understand':'I don’t understand'}</h3><span className="caption">{dateLabel(event.capturedAt)} · {new Date(event.capturedAt).toLocaleTimeString('en',{hour:'2-digit',minute:'2-digit'})}</span></div><Status value={event.status}/></div>{event.kind==='difficult'&&<div className="reported-answers"><span><small>Patient-reported difficulty</small>{event.difficulty}</span><span><small>Patient-reported surroundings</small>{event.environment}</span></div>}{event.analysis?<AcousticResult analysis={event.analysis}/>:<p className="notice">{event.status==='failed'?event.error||'Processing failed. The event is preserved.':'The server is processing this sample. You can leave this page.'}</p>}<div className="interpretation-block"><h4>Astra interpretation</h4><Status value={event.interpretation?.status||'pending'}/>{event.interpretation?.result?<><p>{event.interpretation.result.summary}</p>{event.interpretation.result.clinician_questions?.length&&<ul>{event.interpretation.result.clinician_questions.map((q,i)=><li key={i}>{q}</li>)}</ul>}<p className="caption">{event.interpretation.result.uncertainty}</p></>:<p className="caption">{event.interpretation?.status==='unavailable'?'Astra is unavailable. The real acoustic features above remain available.':'Interpretation is shown only after a complete, validated response. No fitting prescription is provided.'}</p>}</div><details><summary>Capture context and profile snapshot</summary><p className="caption">Phone microphone intended. Actual routing may be unknown. Snapshot: {event.profileSnapshot?.displayName}; follow-up {event.profileSnapshot?.followUpDate}.</p><pre>{JSON.stringify(event.capture,null,2)}</pre></details></article>)}</div>}</section></> }</> }</main><Footer/></>;
}
